// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage/HomeVariantA.tsx": () => import("../components/mockups/homepage/HomeVariantA.tsx"),
  "./components/mockups/homepage/HomeVariantB.tsx": () => import("../components/mockups/homepage/HomeVariantB.tsx")
};
